### ISSUE TITLE
Sleeping breaks the mod

### ISSUE THREAD

**Issue by Yiddan** [DumpsterDave/FS22_PriceWatcher#1]
Good morning ;)

Everytime i go to sleep (ingame ofc) the mod seems to break and stops reporting prices fluctuations every hour.
So for now i use time speed instead.

What i did:
- Test the behavior multiple times
- Start a new fresh save with only PriceWatcher enabled. Waited for the first hours to make sure notifications are working. Then went to sleep, let game "catchup" with all notifications till midnight it seems, then see there is no more notifications for new hours.
- Again, save/reloading the save "fixes" the issue.

Please let me know if you would need any kind of log or additionnal infos :)

**Comment by DumpsterDave** [comment]
Do you have seasons enabled, and if so, how many days are in each season/month?

**Comment by Yiddan** [comment]
Yes i have seasons active. Playing with 3 days/month atm

**Comment by DumpsterDave** [comment]
Thanks, I'll see if I can replicate this later tonight.

**Comment by DumpsterDave** [comment]
This should be fixed with version 1.1.0.1

**Comment by Yiddan** [comment]
Hello DumpsterDave.
I just wanted to come back to confirm the issue is now fixed in version 1.1.0.1
Thank you ;)
