### ISSUE TITLE
attempt to concatenate local 'price' (a nil value)

### ISSUE THREAD

**Issue by Yiddan** [DumpsterDave/FS22_PriceWatcher#4]
Hello dave !
I think i have an issue related to PriceWatcher.
My Elmcreek only loads if i disable the mod.
I got this error in the log:
`MODS/FS22_PriceWatcher/priceWatcher.lua:144: attempt to concatenate local 'price' (a nil value)`
![image](https://user-images.githubusercontent.com/12221160/159039217-adccf958-de7c-46ce-a222-abeb4827462a.png)

It may be related to an incompatibility with another mod? I honestly cannot really tell for sure. The only other "script" mod i enabled before it stopped working is Guidance Steering
[log.txt](https://github.com/DumpsterDave/FS22_PriceWatcher/files/8306012/log.txt)

I'll try to do more tests (aka trying to disable a few other mods, see if it can help :p )

_edit_
I just tried loading this save with GuidanceSteering & ProSeed disabled but PriceWatcher enabled. No success xD

_edit 2_
With only PriceWatcher enabled, still no load and a different error:
`2022-03-18 17:25 Error: Running LUA method 'update'.
dataS/scripts/misc/Logging.lua(41) : bad argument #4 to 'format' (no value)
`

**Comment by DumpsterDave** [comment]
Can you post a copy of your priceWatcher.xml file from your savegame folder?

**Comment by Yiddan** [comment]
Sorry for the answer delay, here is the file :
[priceWatcher.xml.txt](https://github.com/DumpsterDave/FS22_PriceWatcher/files/8308948/priceWatcher.xml.txt)
)

**Comment by DumpsterDave** [comment]
Can you move the priceWatcher.xml out of the savegame directory and try to start without the file present?

**Comment by Yiddan** [comment]
I just tried that, and the save loads normally.

**Comment by Yiddan** [comment]
Could it have anything to do with fact that i have some mods that add "new" types of productions?
I think i just get those recently...
![image](https://user-images.githubusercontent.com/12221160/159119142-55ba1682-8a4e-4ad4-b2dd-01f0d4e47f9e.png)

**Comment by DumpsterDave** [comment]
Most likely.  That or one that was present at some point, but isn't anymore.  It looks like it's picking up the additional ones correctly.  Should be a simple fix though.

**Comment by DumpsterDave** [comment]
give release 1.1.0.3 a try.  Let me know if that resolves the issue.

**Comment by Yiddan** [comment]
Thanks, i will report back asap :)

Edit: My game has loaded perfectly, ill make sure to come back to you if i have any issue again later.
Thank you for helping & fixing the mod ;)

(As a sidenote, PriceWatcher doesnt seem to track/report any custom/new product prices. Do you think that could be possible? I suppose with time, players will have more and more products added by mods, and imo it would be great if pricewatcher could natively support that)

**Comment by DumpsterDave** [comment]
In theory it should track anything that is in the game tables (native or otherwise).  Open a new issue for that and I'll mark it as an enhancement/feature request.  If you have any specific mods that you are using, please list them too so that I can use them as a reference/functionality check.

**Comment by Yiddan** [comment]
I opened and read through my pricewatchter.xml file, and i saw that "some" of the custom products my current mods add are currently properly tracked. I should have done that before asking about it so sorry for asking. I think i just didnt play long enough to see those items in the hourly notifications.
But, if i notice any issue relative to that subject ill make sure to open a new topic as you asked me to ;)

**Comment by FirenzeIT** [comment]
Hello @DumpsterDave, it's possible to update this mod with last update of game and with last crop/fruits please?? Thank you.
